/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface": "#d8e3fb",
        "surface-container-lowest": "#040e1f",
        "surface-container": "#152031",
        "on-tertiary-container": "#212c27",
        "inverse-surface": "#d8e3fb",
        "on-primary-container": "#0d0096",
        "background": "#081425",
        "surface-container-high": "#1f2a3c",
        "outline-variant": "#464554",
        "tertiary": "#bdcac1",
        "on-primary-fixed": "#07006c",
        "tertiary-fixed-dim": "#bdcac1",
        "on-secondary-fixed": "#111c2d",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#3e4943",
        "error-container": "#93000a",
        "secondary-container": "#3e495d",
        "on-surface-variant": "#c7c4d7",
        "on-background": "#d8e3fb",
        "tertiary-fixed": "#d9e6dd",
        "tertiary-container": "#87948c",
        "surface-container-low": "#111c2d",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-dim": "#081425",
        "on-secondary": "#263143",
        "on-tertiary-fixed": "#131e19",
        "on-tertiary": "#27332d",
        "primary-container": "#8083ff",
        "primary": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#c0c1ff",
        "outline": "#908fa0",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#3c475a",
        "on-error": "#690005",
        "secondary": "#bcc7de",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-container": "#aeb9d0",
        "secondary-fixed": "#d8e3fb",
        "inverse-on-surface": "#263143",
        "surface-variant": "#2a3548",
        "on-primary": "#1000a9",
        "surface": "#081425",
        "surface-tint": "#c0c1ff",
        "surface-container-highest": "#2a3548",
        "surface-bright": "#2f3a4c",
        "inverse-primary": "#494bd6"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
